// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYyfODCq5zIN9Yq59G7mgomVlYvinPa8I',
    appId: '1:819699724391:web:7c6b40b43f49ff0e52a4c2',
    messagingSenderId: '819699724391',
    projectId: 'my-new-dart-project',
    authDomain: 'my-new-dart-project.firebaseapp.com',
    storageBucket: 'my-new-dart-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBj6yijUbVXxJa6Jn5hAp4q4QMF8KeA7BU',
    appId: '1:819699724391:android:70ab99e279b64fa952a4c2',
    messagingSenderId: '819699724391',
    projectId: 'my-new-dart-project',
    storageBucket: 'my-new-dart-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvyDopliUuDbMPpKCzvPt4Zlils42l1p0',
    appId: '1:819699724391:ios:27c6773b2829bfd352a4c2',
    messagingSenderId: '819699724391',
    projectId: 'my-new-dart-project',
    storageBucket: 'my-new-dart-project.firebasestorage.app',
    iosBundleId: 'com.example.learningdart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvyDopliUuDbMPpKCzvPt4Zlils42l1p0',
    appId: '1:819699724391:ios:27c6773b2829bfd352a4c2',
    messagingSenderId: '819699724391',
    projectId: 'my-new-dart-project',
    storageBucket: 'my-new-dart-project.firebasestorage.app',
    iosBundleId: 'com.example.learningdart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYyfODCq5zIN9Yq59G7mgomVlYvinPa8I',
    appId: '1:819699724391:web:004b921ed5dbb3d352a4c2',
    messagingSenderId: '819699724391',
    projectId: 'my-new-dart-project',
    authDomain: 'my-new-dart-project.firebaseapp.com',
    storageBucket: 'my-new-dart-project.firebasestorage.app',
  );
}
